# Generated by Django 4.2.23 on 2025-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_messages_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
