# Generated by Django 4.2.23 on 2025-08-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_messages_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Tasks',
        ),
    ]
